#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param env PYTHONPATH=/opt/tuya-homekit/lib
    procd_set_param command python3 /opt/tuya-homekit/tuya-homekit-bridge.py
    procd_set_param directory /opt/tuya-homekit
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
